### PR TITLE
Updating for v9: update dependencies and CI

### PR DESCRIPTION
**Pull request by Ranieri93**
Resolves issue #63.

Hello! 

This PR is linked to [this](https://github.com/pinojs/koa-pino-logger/issues/63)

To be noted:
Even on master, I have one test failing no matter which node version is used or dependencies update, I'm trying to figure out if it is something specific for me, or not.

@jsumners

### CODE REVIEW

**Comment by jsumners** [comment]
The issue is that when the test hits the line at https://github.com/pinojs/pino-std-serializers/blob/e0f61fa84e36aa1b79755e884da974ae5864a548/lib/res.js#L37 it evaluates `res.headersSent` to `false` and thus sets `res.statusCode = null`. I assume this has something to do with the way Koa does things. Someone will need to dig in to why Koa has started invoking this failure case instead of passing correctly. My initial testing indicates it fails all the way back to `koa@2.0.0`, though.

**Comment by Ranieri93** [comment]
How do you think we should proceed then? 
Putting null in the test isn't a solution, should I start digging into Koa and understand why it started behaving like this? 
Also, how were those tests ok in the CI in the past? `koa@2.0.0` is like 8 years old

**Comment by jsumners** [comment]
Inspecting the intention of the test and determining if what needs to be fixed is the core of the work. It could be the test or something else. 

I have no idea if the test ever worked or didn't. But I doubt this test failed when it was added. So something else must've changed.

**Comment by jsumners** [comment]
The culprit is https://github.com/pinojs/pino-std-serializers/pull/103.

The actual issue is that https://github.com/pinojs/pino-http/blob/9bf08025852013b5927b5b275ec5bc23fb38a015/logger.js#L197-L198 is listening for `close` and `finish` events with the same handler and both events are fired when a connection ends.

I'm really not sure what to do here. My initial inclination is the update `pino-http` to recognize when event has been fired and do something different in each case. But maybe it's okay to `res.flushHeaders()` somewhere before we attempt to read `res.headersSent`?

@mcollina do you have any ideas on how to solve this issue. Basically, `koa-pino-logger` has been been a bit broken since the merge and release of the above linked issue.

<details>
<summary>Events example</summary>

Note that both `close` and `finish` are fired.

```js
'use strict'

const http = require('node:http')

const server = http.createServer((req, res) => {
  res.on('close', () => console.log('!!! close'))
  res.on('finish', () => console.log('!!! finish'))

  res.write('ok')
  res.end()
})

server.listen(8080, '127.0.0.1', (err) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }

  http.get('http://127.0.0.1:8080/', (res) => {
    res.on('data', d => {
      console.log(d.toString())
    })

    res.on('end', () => {
      server.close(() => {
        console.log('done')
      })
    })
  })
})
```

</details>

**Pull request closed without merging**
