### PR TITLE
upgrade pino-http

### PR DESCRIPTION
**Pull request by katlimruiz**
It corresponds to https://github.com/pinojs/pino-http/pull/77

All tests have passed.

### CODE REVIEW

**Comment by katlimruiz** [comment]
Hi, 
@davidmarkclements any chance we can do this merge? It is just the upgrade to the library

**Comment by katlimruiz** [comment]
any help here please?

**Comment by katlimruiz** [comment]
@davidmarkclements any chance you can merge this pull request?

**Comment by Fdawgs** [comment]
This has been resolved by #27 and #30

**Pull request closed without merging**
