### PR TITLE
ci: add nodejs v16 to test matrix

### PR DESCRIPTION
**Pull request by Fdawgs**

### CODE REVIEW

**Comment by Fdawgs** [comment]
@mcollina was planning on taking a further pass at this to bring it in line with the other pino repos. Is it still maintained/supported?

**Comment by mcollina** [comment]
I can probably give you commit access if you'd like to help maintaining it. We are a bit strained atm.

**Comment by Fdawgs** [comment]
No worries @mcollina. More than happy to help!

**Comment by mcollina** [comment]
@Fdawgs I've added you to this repo. Feel free to update/maintain it! Open an issue when you are ready for a release.

**Pull request merged**
