### PR TITLE
Catching error instead of overriding `onerror`

### LINKED ISSUE #10: Not working with error reporting middlewares.
The errors passed to these error reporting middlewares will be caught, and then Koa will not calling ``context.onerror``:

- [koa-error](https://github.com/koajs/error/)
- [koa-json-error](https://github.com/koajs/json-error)
- [Some other error reporting middlewares](https://github.com/koajs/koa/wiki#error-reporting)

Maybe overriding `onerror` isn't a good idea I think?

### PR DESCRIPTION
**Pull request by imyelo**
Fix #10

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Can you please add benchmark output of master vs pr

**Comment by imyelo** [comment]
Taken on 3.20GHz i5, 8GiB of RAM, Ubuntu v16.04, Node.js v8.9.1, Koa v2.5.0.

### before vs after

#### benchmarks/pino-error-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg    Stdev  Max    
    Latency (ms) 0      0      0      
    Req/Sec      1246.6 34.79  1278   
    Bytes/Sec    224 kB 6.8 kB 231 kB 

    0 2xx responses, 12466 non 2xx responses
    12k requests in 10s, 2.26 MB read

->

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg    Stdev   Max    
    Latency (ms) 0      0       0      
    Req/Sec      1239.3 34.52   1263   
    Bytes/Sec    224 kB 4.92 kB 229 kB 

    0 2xx responses, 12393 non 2xx responses
    12k requests in 10s, 2.24 MB read

#### benchmarks/pino-extreme-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg     Stdev   Max    
    Latency (ms) 21.35   4.73    53.67  
    Req/Sec      4575.61 125.34  4688   
    Bytes/Sec    698 kB  19.7 kB 713 kB 

    46k requests in 10s, 6.95 MB read

->

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg    Stdev  Max    
    Latency (ms) 21.73  5.01   61.47  
    Req/Sec      4494.8 153.18 4725   
    Bytes/Sec    682 kB 21 kB  718 kB 

    45k requests in 10s, 6.83 MB read

#### benchmarks/pino-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg     Stdev   Max    
    Latency (ms) 21.62   4.93    61.1   
    Req/Sec      4516.46 147.33  4644   
    Bytes/Sec    684 kB  28.9 kB 706 kB 

    50k requests in 11s, 7.55 MB read

->

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg    Stdev  Max    
    Latency (ms) 21.68  4.92   60.65  
    Req/Sec      4504.8 111.73 4587   
    Bytes/Sec    688 kB 22 kB  697 kB 

    45k requests in 10s, 6.85 MB read

#### benchmarks/raw-just-pino-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg     Stdev   Max     
    Latency (ms) 9.71    4.05    40.46   
    Req/Sec      9780    360.95  9989    
    Bytes/Sec    1.07 MB 34.4 kB 1.11 MB 

    98k requests in 10s, 10.9 MB read

->

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg     Stdev   Max    
    Latency (ms) 9.74    4.3     45.61  
    Req/Sec      9712.8  329.37  9867   
    Bytes/Sec    1.07 MB 34.4 kB 1.1 MB 

    97k requests in 10s, 10.8 MB read

### others
#### benchmarks/bunyan-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg    Stdev   Max    
    Latency (ms) 34.39  4.45    76.54  
    Req/Sec      2864.2 66.86   2945   
    Bytes/Sec    434 kB 12.7 kB 448 kB 

    29k requests in 10s, 4.35 MB read

#### benchmarks/morgan-server.js

    Running 10s test @ http://localhost:3000
    100 connections

    Stat         Avg      Stdev  Max     
    Latency (ms) 6.34     1.95   63.71   
    Req/Sec      15056.37 1815.9 15946   
    Bytes/Sec    2.3 MB   292 kB 2.42 MB 

    166k requests in 11s, 25.2 MB read

**Comment by davidmarkclements** [comment]
ok that's awesome - using onerror override made a big difference performance wise, it seems with Turbofan there's essentially no difference. 

thanks for this @imyelo merging and releasing now

**Comment by davidmarkclements** [comment]
2.1.1 published

**Pull request merged**
